# Model arguments
model_name_or_path: cui54/qwen2.5-3b_b4_t2_LR_1e-5_1000_augment
model_revision: main
tokenizer_name_or_path: cui54/qwen2.5-3b_b4_t2_LR_1e-5_1000_augment
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# TODO: Data training arguments
dataset_mixer:
  /local3/cui54/summarization_adapter/summarization_data: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
do_eval: False
eval_strategy: epoch
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 1.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 1024
max_steps: -1
num_train_epochs: 2
output_dir: weights/qwen2.5-3b_b4_t2_LR_1e-5_1000_augment_stage2
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
use_liger: True
warmup_ratio: 0.1